#pragma once
#include "../road/RoadNetwork.hpp"

/// @brief 案内標識（GuideSignPlacement）の独立セーブファイル I/O
/// @details plan/21_guide_sign_spec.md §5
///
/// ファイル構成:
/// - global/guide_signs.json       — 手動配置標識のメタデータ
/// - global/guide_signs_cache/     — 描画済み看板 PNG キャッシュ
///
/// 自動生成標識 (autoGenerated=true) は JSON に保存しない。
/// ロード後 `recomputeAllAutoGuideSigns()` で再生成される。
namespace GuideSignStorage
{
	/// @brief 手動配置の GuideSignPlacement を JSON に書き出す
	/// @param path  出力先ファイルパス (global/guide_signs.json)
	/// @return 成功なら true
	bool writeJson(const FilePath& path, const RoadNetwork& network);

	/// @brief JSON を読み込み、RoadNetwork に addGuideSignRaw する
	/// @note 呼び出し側で clearGuideSigns してから呼ぶこと
	bool readJson(const FilePath& path, RoadNetwork& network);
}
