#include "GuideSignStorage.hpp"

namespace
{
	JSON signToJson(const GuideSignPlacement& g)
	{
		JSON j;
		j[U"id"]             = g.id;
		j[U"parentEdgeId"]   = g.parentEdgeId;
		j[U"kind"]           = static_cast<int>(g.kind);
		j[U"nodeEndId"]      = g.nodeEndId;
		j[U"arcOffset"]      = g.arcOffset;
		j[U"lateralOffset"]  = g.lateralOffset;
		j[U"poleHeight"]     = g.poleHeight;
		j[U"autoGenerated"]  = g.autoGenerated;
		j[U"sourceNodeId"]   = g.sourceNodeId;
		j[U"widthOverride"]  = g.widthOverride;
		j[U"heightOverride"] = g.heightOverride;
		j[U"bgColor"]        = Array<double>{ g.bgColor.r, g.bgColor.g, g.bgColor.b, g.bgColor.a };
		j[U"showReading"]    = g.showReading;

		JSON elems;
		for (const auto& el : g.elements)
		{
			JSON ej;
			ej[U"kind"]        = static_cast<int>(el.kind);
			ej[U"posX"]        = el.posX;
			ej[U"posY"]        = el.posY;
			ej[U"scale"]       = el.scale;
			ej[U"text"]        = el.text;
			ej[U"reading"]     = el.reading;
			ej[U"arrowAngle"]  = el.arrowAngle;
			ej[U"arrowLength"] = el.arrowLength;
			ej[U"value"]       = el.value;
			elems.push_back(ej);
		}
		j[U"elements"] = elems;
		return j;
	}

	GuideSignPlacement signFromJson(const JSON& j)
	{
		GuideSignPlacement g;
		g.id             = j[U"id"].get<int>();
		g.parentEdgeId   = j[U"parentEdgeId"].get<int>();
		g.kind           = static_cast<GuideSignKind>(j[U"kind"].get<int>());
		g.nodeEndId      = j[U"nodeEndId"].get<int>();
		g.arcOffset      = j[U"arcOffset"].get<float>();
		g.lateralOffset  = j[U"lateralOffset"].get<float>();
		g.poleHeight     = j[U"poleHeight"].get<float>();
		g.autoGenerated  = j[U"autoGenerated"].get<bool>();
		g.sourceNodeId   = j[U"sourceNodeId"].get<int>();
		g.widthOverride  = j[U"widthOverride"].get<float>();
		g.heightOverride = j[U"heightOverride"].get<float>();
		const auto& bg   = j[U"bgColor"];
		g.bgColor        = ColorF{ bg[0].get<double>(), bg[1].get<double>(), bg[2].get<double>(), bg[3].get<double>() };
		g.showReading    = j[U"showReading"].get<bool>();
		for (const auto& [key, val] : j[U"elements"])
		{
			SignElement el;
			el.kind        = static_cast<SignElementKind>(val[U"kind"].get<int>());
			el.posX        = val[U"posX"].get<float>();
			el.posY        = val[U"posY"].get<float>();
			el.scale       = val[U"scale"].get<float>();
			el.text        = val[U"text"].get<String>();
			el.reading     = val[U"reading"].get<String>();
			el.arrowAngle  = val[U"arrowAngle"].get<float>();
			el.arrowLength = val[U"arrowLength"].get<float>();
			el.value       = val[U"value"].get<float>();
			g.elements << el;
		}
		return g;
	}
}

bool GuideSignStorage::writeJson(const FilePath& path, const RoadNetwork& network)
{
	JSON root;
	JSON signs;
	int savedCount = 0;
	for (const auto& g : network.guideSigns())
	{
		if (g.id < 0) continue;
		if (g.autoGenerated) continue;  // 自動生成は保存しない
		signs.push_back(signToJson(g));
		++savedCount;
	}
	root[U"signs"]  = signs;
	root[U"count"]  = savedCount;
	return root.save(path);
}

bool GuideSignStorage::readJson(const FilePath& path, RoadNetwork& network)
{
	const JSON root = JSON::Load(path);
	if (!root) return false;
	for (const auto& [key, val] : root[U"signs"])
	{
		const auto g = signFromJson(val);
		if (g.id < 0 || g.parentEdgeId < 0) continue;
		network.addGuideSignRaw(g);
	}
	return true;
}
