#pragma once
#include "RoadTypes.hpp"

class RoadNetwork;

// RoadSignType / RoadSignPlacement は RoadTypes.hpp で定義（循環依存回避のため）

/// @brief 標識メッシュ生成・自動推論
namespace RoadSign
{
	// ===== 寸法定数 =====

	constexpr double kPoleRadius_m   = 0.03;   ///< ポール半径 (φ60mm)
	constexpr double kStopBoardSide_m = 0.8;   ///< 止まれ標識: 一辺
	constexpr double kBoardThickness_m = 0.02;
	constexpr double kBoardCenterFromPoleTop_m = 0.4; ///< ポール頂上から看板中心までの距離 [m]
	constexpr double kSideMargin_m   = 0.5;    ///< 路肩外側へのマージン [m]

	// ===== メッシュ ColorF =====

	const ColorF kPoleColor    { 0.65, 0.65, 0.7 };
	const ColorF kBoardRedBg   { 0.85, 0.10, 0.10 };
	const ColorF kBoardWhiteBorder { 0.95, 0.95, 0.95 };

	// ===== API =====

	/// @brief ポールメッシュ（地面〜poleHeight 高さの円柱）
	/// @details 戻り値の MeshData は **ローカル座標**:
	///   原点 = ポール接地点（地面）
	///   Y 軸: 上向き
	MeshData CreatePoleMesh(float poleHeight);

	/// @brief 看板メッシュ（種別ごとの形状）
	/// @details ローカル座標:
	///   原点 = 看板中心
	///   X-Y 平面: 看板面（X 右、Y 上）
	///   Z 軸: 看板の前面法線（手前を向く方向）
	MeshData CreateBoardMesh(RoadSignType type);

	/// @brief 国道標識の看板メッシュ（assets/signs/national_road_sign.obj をロード）
	/// @details ローカル座標: 原点=看板中心, X 右・Y 上・Z 前面法線
	///   OBJ は Test プロジェクトで national_road_sign.png の輪郭から事前生成。
	///   UV: u = 0.5 − x/size, v = 0.5 − y/size（テクスチャ全域をマッピング）
	MeshData CreateOnigiriBoard(float size);

	/// @brief 1エッジ分の自動生成 Stop 標識を作る
	/// @details
	///   `attachment.control == TrafficControl::Stop` のノード端それぞれに
	///   `autoGenerated=true` の Stop 標識を作る。
	/// @return 自動生成された配置リスト
	Array<RoadSignPlacement> InferAutoForEdge(const RoadEdge& edge, const RoadNetwork& network);
}
