#include "RoadNetwork.hpp"
#include "../debug/DebugLog.hpp"
#include "RoadSign.hpp"
#include "GuideSign.hpp"

void RoadNetwork::recomputeAutoSignsForEdge(int edgeId)
{
	RoadEdge* edge = getEdge(edgeId);
	if (!edge) return;
	// 既存の自動エントリを削除（手動配置は保持）
	edge->signs.remove_if([](const RoadSignPlacement& s) { return s.autoGenerated; });
	if (!edge->hasRoadLanes()) { return; }
	// 自動生成
	const auto autos = RoadSign::InferAutoForEdge(*edge, *this);
	for (const auto& s : autos) edge->signs << s;
}

void RoadNetwork::recomputeAllAutoSigns()
{
	for (auto& e : m_edges)
	{
		if (e.id < 0) continue;
		recomputeAutoSignsForEdge(e.id);
	}
}

void RoadNetwork::recomputeAutoGuideSignsForEdge(int edgeId)
{
	const RoadEdge* edge = getEdge(edgeId);
	if (!edge) return;
	recomputeAutoGuideSignsForNode(edge->nodeA);
	recomputeAutoGuideSignsForNode(edge->nodeB);
}

void RoadNetwork::recomputeAutoGuideSignsForNode(int nodeId, const GuideSign::AutoPlacementClearance* clearance)
{
	// このノード起点の自動案内標識だけを張り直し、手動配置や他ノード由来の標識は残す。
	// sourceNodeId == nodeId の自動標識を一括削除
	Array<int> removeIds;
	for (const auto& g : m_guideSigns)
	{
		if (g.id >= 0 && g.autoGenerated && g.sourceNodeId == nodeId)
		{
			removeIds << g.id;
		}
	}
	for (int id : removeIds)
	{
		removeGuideSign(id);
	}

	// nodeId に接続する全エッジで InferAutoForEdge を呼び、sourceNodeId==nodeId のものだけ追加
	const RoadNode* node = getNode(nodeId);
	if (!node)
	{
		return;
	}
	for (const auto& att : node->attachments)
	{
		const RoadEdge* edge = getEdge(att.edgeId);
		if (!edge || !edge->hasRoadLanes())
		{
			continue;
		}
		auto autos = GuideSign::InferAutoForEdge(*edge, *this, clearance);
		for (auto& g : autos)
		{
			if (g.sourceNodeId != nodeId)
			{
				continue;
			}
			if (g.parentEdgeId < 0)
			{
				g.parentEdgeId = att.edgeId;
			}
			addGuideSign(std::move(g));
		}
	}
}

void RoadNetwork::recomputeAllAutoGuideSigns()
{
	const GuideSign::AutoPlacementClearance clearance{ *this };
	for (auto& n : m_nodes)
	{
		if (n.id < 0) continue;
		recomputeAutoGuideSignsForNode(n.id, &clearance);
	}
	int generated=0, violations=0;
	for (const auto& sign : m_guideSigns)
	{
		if (sign.id<0 || !sign.autoGenerated) { continue; }
		const auto* edge=getEdge(sign.parentEdgeId);
		const auto curve=getBezier(sign.parentEdgeId);
		if (!edge || !curve) { continue; }
		++generated;
		const float arc=sign.nodeEndId==edge->nodeA?sign.arcOffset:curve->totalLength-sign.arcOffset;
		if (!clearance.allows(curve->positionAt(arc),edge->totalWidth()*0.5+4.0)) { ++violations; }
	}
	DBG_LOG(U"[GuideSignClearance] generated={} exclusionViolations={} clearanceM=30"_fmt(generated,violations));
}

// ─────────────────────────────────────────────────────────────────────────────
// GuideSign CRUD
// ─────────────────────────────────────────────────────────────────────────────

int RoadNetwork::addGuideSign(GuideSignPlacement sign)
{
	sign.id = m_nextGuideSignId++;
	int slot;
	if (!m_freeGuideSignSlots.isEmpty())
	{
		slot = m_freeGuideSignSlots.back();
		m_freeGuideSignSlots.pop_back();
		m_guideSigns[slot] = std::move(sign);
	}
	else
	{
		slot = static_cast<int>(m_guideSigns.size());
		m_guideSigns << std::move(sign);
	}
	m_guideSignIdToIdx[m_guideSigns[slot].id] = slot;
	return m_guideSigns[slot].id;
}

void RoadNetwork::addGuideSignRaw(const GuideSignPlacement& sign)
{
	if (sign.id < 0) return;
	if (sign.id >= m_nextGuideSignId) m_nextGuideSignId = sign.id + 1;
	int slot;
	if (!m_freeGuideSignSlots.isEmpty())
	{
		slot = m_freeGuideSignSlots.back();
		m_freeGuideSignSlots.pop_back();
		m_guideSigns[slot] = sign;
	}
	else
	{
		slot = static_cast<int>(m_guideSigns.size());
		m_guideSigns << sign;
	}
	m_guideSignIdToIdx[sign.id] = slot;
}

void RoadNetwork::removeGuideSign(int signId)
{
	const int idx = guideSignIndex(signId);
	if (idx < 0) return;
	m_guideSigns[idx].id = -1;
	m_guideSignIdToIdx.erase(signId);
	m_freeGuideSignSlots << idx;
}

void RoadNetwork::removeGuideSignsByEdge(int edgeId)
{
	Array<int> ids;
	for (const auto& g : m_guideSigns)
		if (g.id >= 0 && g.parentEdgeId == edgeId) ids << g.id;
	for (int id : ids) removeGuideSign(id);
}

GuideSignPlacement* RoadNetwork::getGuideSign(int id)
{
	const int idx = guideSignIndex(id);
	return (idx >= 0) ? &m_guideSigns[idx] : nullptr;
}

const GuideSignPlacement* RoadNetwork::getGuideSign(int id) const
{
	const int idx = guideSignIndex(id);
	return (idx >= 0) ? &m_guideSigns[idx] : nullptr;
}

void RoadNetwork::clearGuideSigns()
{
	m_guideSigns.clear();
	m_guideSignIdToIdx.clear();
	m_freeGuideSignSlots.clear();
	m_nextGuideSignId = 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// NamedDestination
// ─────────────────────────────────────────────────────────────────────────────

void RoadNetwork::addNamedDestination(int nodeId, const String& name, const String& reading, uint8 tier)
{
	if (nodeId < 0 || name.isEmpty()) return;
	// 既登録なら tier を昇格（数値が小さい = 優先度高い）
	if (auto it = m_destByNode.find(nodeId); it != m_destByNode.end())
	{
		NamedDestination& d = m_namedDestinations[it->second];
		d.name    = name;
		d.reading = reading;
		if (tier < d.tier) d.tier = tier;
		return;
	}
	m_destByNode[nodeId] = static_cast<int>(m_namedDestinations.size());
	m_namedDestinations << NamedDestination{ nodeId, name, reading, tier };
}

const String* RoadNetwork::getDestinationReading(int nodeId) const
{
	const auto it = m_destByNode.find(nodeId);
	if (it == m_destByNode.end()) return nullptr;
	const String& r = m_namedDestinations[it->second].reading;
	return r.isEmpty() ? nullptr : &r;
}

void RoadNetwork::clearNamedDestinations()
{
	m_namedDestinations.clear();
	m_destByNode.clear();
}

const String* RoadNetwork::getDestinationName(int nodeId) const
{
	const auto it = m_destByNode.find(nodeId);
	if (it == m_destByNode.end()) return nullptr;
	return &m_namedDestinations[it->second].name;
}

uint8 RoadNetwork::getDestinationTier(int nodeId) const
{
	const auto it = m_destByNode.find(nodeId);
	if (it == m_destByNode.end()) return 255;
	return m_namedDestinations[it->second].tier;
}

// ─────────────────────────────────────────────────────────────────────────────
// RoadRoute API
// ─────────────────────────────────────────────────────────────────────────────

