#pragma once
#include "RoadTypes.hpp"

class RoadNetwork;

// RoadSignType / RoadSignPlacement は RoadTypes.hpp で定義（循環依存回避のため）

/// @brief 標識メッシュ生成・自動推論
namespace RoadSign
{
	// ===== 寸法定数 =====

	constexpr double kPoleRadius_m   = 0.03;   ///< ポール半径 (φ60mm)
	constexpr double kRouteBoardSize_m = 0.8;  ///< 国道標識（おにぎり）: 外接サイズ
	constexpr double kBoardCenterFromPoleTop_m = 0.4; ///< ポール頂上から看板中心までの距離 [m]
	constexpr double kSideMargin_m   = 0.5;    ///< 路肩外側へのマージン [m]
	constexpr float  kDefaultPoleHeight_m = 2.5f;    ///< 規制標識のポール高さ既定値
	constexpr float  kRoutePoleHeight_m   = 3.5f;    ///< 国道標識のポール高さ既定値
	constexpr float  kBoardForwardShift_m = 0.05f;   ///< 看板をポール正面に出すためのオフセット [m]

	// ===== メッシュ ColorF =====

	const ColorF kPoleColor    { 0.65, 0.65, 0.7 };

	// ===== API =====

	/// @brief ポールメッシュ（地面〜poleHeight 高さの円柱、実寸で生成）
	/// @details 戻り値の MeshData は **ローカル座標**:
	///   原点 = ポール接地点（地面）
	///   Y 軸: 上向き
	/// @note 実寸のため、描画時に Y スケールしないこと。
	MeshData CreatePoleMesh(float poleHeight);

	/// @brief RoadSign ポール/看板メタデータ（assets/signs/sign_pole.json）
	/// @details 全 RoadSign 種別で共通のポール（2.5m 円柱）を使用。
	///   座標系:
	///     X: 道路に対して横方向（車線と直交）
	///     Y: 垂直（上向き）。ポール接地 = 0
	///     Z: 道路の長手方向（driver の進行方向と逆＝手前へ伸ばす軸）
	struct PoleMetadata
	{
		float poleHeight = 2.5f;
		float offsetX    = 0.0f;
		float offsetY    = 2.1f;
		float offsetZ    = 0.05f;
	};

	/// @brief 共通ポールのメタデータ（JSON ロード、キャッシュ）
	const PoleMetadata& poleMetadata();

	/// @brief poleMetadata() のキャッシュを破棄（次回呼び出し時に JSON から再ロード）
	void reloadPoleMetadata();

	/// @brief 標識種別の表示情報
	/// @details 形状 OBJ は種別をまたいで共用可（例: Stop と Yield は inverted_triangle.obj）。
	///   textureAssetName が空の場合は動的生成テクスチャ（NationalRoute の号数合成等）。
	struct SignVisual
	{
		RoadSignCategory category;
		StringView       shapeObjPath;     ///< 形状 OBJ の相対パス (assets/signs/<cat>/xxx.obj)
		StringView       textureAssetName; ///< Asset:: 定数。空なら動的解決
	};

	/// @brief RoadSignType → SignVisual 解決
	const SignVisual& visualOf(RoadSignType type);

	/// @brief 看板メッシュ（形状 OBJ をロード）
	/// @details ローカル座標: 原点=看板中心, X 右・Y 上・Z 前面法線。
	///   形状は RoadSignCategory ごとに assets/signs/<category>/<shape>.obj に配置。
	MeshData CreateBoardMesh(RoadSignType type);

	/// @brief 看板中心がポール頂上から下方向に何 m 下がった位置かを返す
	double BoardCenterFromPoleTop(RoadSignType type);

	/// @brief Roadbed 部品の左端 / 右端オフセット [m]
	/// @details Roadbed が無い場合は ±totalWidth/2 にフォールバック
	struct RoadbedExtents { float left; float right; };
	RoadbedExtents roadbedExtentsOf(const RoadEdge& edge);

	/// @brief 1エッジ分の自動生成 Stop 標識を作る
	/// @details
	///   `attachment.control == TrafficControl::Stop` のノード端それぞれに
	///   `autoGenerated=true` の Stop 標識を作る。
	/// @return 自動生成された配置リスト
	Array<RoadSignPlacement> InferAutoForEdge(const RoadEdge& edge, const RoadNetwork& network);
}
