#include "RoadSign.hpp"
#include "RoadNetwork.hpp"
#include "ObjParser.hpp"

namespace
{
	/// @brief Vertex3D を生成する
	Vertex3D mkVert(double x, double y, double z, float u, float v,
	                double nx = 0.0, double ny = 1.0, double nz = 0.0)
	{
		Vertex3D vt;
		vt.pos    = Float3{ static_cast<float>(x), static_cast<float>(y), static_cast<float>(z) };
		vt.normal = Float3{ static_cast<float>(nx), static_cast<float>(ny), static_cast<float>(nz) };
		vt.tex    = Float2{ u, v };
		return vt;
	}

	/// @brief XZ 平面の半幅 r、高さ h の円柱を生成（底面 Y=0、上面 Y=h）
	MeshData makeCylinder(double r, double h, int segments = 12)
	{
		MeshData md;
		md.vertices.reserve((segments + 1) * 2);
		md.indices.reserve(segments * 2);

		// 側面
		for (int i = 0; i <= segments; ++i)
		{
			const double theta = (i / static_cast<double>(segments)) * Math::TwoPi;
			const double cx = Math::Cos(theta) * r;
			const double cz = Math::Sin(theta) * r;
			const float u = static_cast<float>(i) / segments;
			md.vertices << mkVert(cx, 0.0, cz, u, 0.0f, cx / r, 0.0, cz / r);
			md.vertices << mkVert(cx, h,   cz, u, 1.0f, cx / r, 0.0, cz / r);
		}

		for (int i = 0; i < segments; ++i)
		{
			const uint32 b = static_cast<uint32>(i * 2);
			md.indices << TriangleIndex32{ b,     b + 2, b + 1 };
			md.indices << TriangleIndex32{ b + 1, b + 2, b + 3 };
		}

		return md;
	}
}

MeshData RoadSign::CreatePoleMesh(float poleHeight)
{
	return makeCylinder(kPoleRadius_m, static_cast<double>(poleHeight), 10);
}

MeshData RoadSign::CreateBoardMesh(RoadSignType type)
{
	MeshData md;
	if (type != RoadSignType::Stop) return md;

	// 一辺 0.8m の逆三角形（頂点が下）
	// ローカル座標: 中心 = 重心 (X=0, Y=0)
	// 正三角形の中心から各頂点への距離 = side / sqrt(3) ≈ 0.462m
	// 上辺の Y = side / (2*sqrt(3)) ≈ 0.231m
	// 下頂点の Y = -side / sqrt(3) ≈ -0.462m
	const double side = kStopBoardSide_m;
	const double half = side * 0.5;
	const double topY = side / (2.0 * Math::Sqrt(3.0));
	const double botY = -side / Math::Sqrt(3.0);
	const double th   = kBoardThickness_m * 0.5;

	// 前面（+Z 法線）
	const uint32 base = static_cast<uint32>(md.vertices.size());
	md.vertices << mkVert(-half, topY,  th, 0.0f, 0.0f, 0, 0, 1);  // 左上
	md.vertices << mkVert( half, topY,  th, 1.0f, 0.0f, 0, 0, 1);  // 右上
	md.vertices << mkVert( 0.0,  botY,  th, 0.5f, 1.0f, 0, 0, 1);  // 下頂点
	md.indices << TriangleIndex32{ base, base + 1, base + 2 };

	// 背面（-Z 法線、巻き順逆）
	const uint32 base2 = static_cast<uint32>(md.vertices.size());
	md.vertices << mkVert(-half, topY, -th, 0.0f, 0.0f, 0, 0, -1);
	md.vertices << mkVert( half, topY, -th, 1.0f, 0.0f, 0, 0, -1);
	md.vertices << mkVert( 0.0,  botY, -th, 0.5f, 1.0f, 0, 0, -1);
	md.indices << TriangleIndex32{ base2, base2 + 2, base2 + 1 };

	return md;
}

MeshData RoadSign::CreateOnigiriBoard([[maybe_unused]] float size)
{
	// assets/signs/national_road_sign.obj を読み込んで MeshData を返す
	// OBJ は Test プロジェクトで事前生成済み（0.8m スケール、UV 正規化済み）
	const auto parsed = ObjParser::parse(U"assets/signs/national_road_sign.obj");
	if (parsed.isEmpty()) return {};

	// 前面・背面2オブジェクトを結合（OBJ 内に front/back として格納）
	MeshData md;
	for (const auto& pd : parsed)
	{
		if (pd.isEmpty()) continue;
		const uint32 base = static_cast<uint32>(md.vertices.size());
		md.vertices.insert(md.vertices.end(), pd.vertices.begin(), pd.vertices.end());
		for (const auto& t : pd.indices)
			md.indices << TriangleIndex32{ base + t.i0, base + t.i1, base + t.i2 };
	}
	return md;
}

Array<RoadSignPlacement> RoadSign::InferAutoForEdge(const RoadEdge& edge, const RoadNetwork& network)
{
	Array<RoadSignPlacement> out;

	// 道路総幅の半分（横方向オフセット計算用）
	const float halfWidth = edge.totalWidth() * 0.5f;
	const float lateralAbs = halfWidth + static_cast<float>(kSideMargin_m);

	// nodeA, nodeB それぞれについて attachment.control を見て自動生成
	const auto checkNode = [&](int nodeId) {
		const RoadNode* node = network.getNode(nodeId);
		if (!node) return;
		const EdgeAttachment* att = node->getAttachment(edge.id);
		if (!att) return;

		if (att->control == TrafficControl::Stop)
		{
			RoadSignPlacement sp;
			sp.type      = RoadSignType::Stop;
			sp.nodeEndId = nodeId;
			sp.arcOffset = 0.0f;  // cutoff 位置
			// driver の左側に配置:
			//   nodeId == nodeB → driver は A→B → driver の左 = lateralOffset 負
			//   nodeId == nodeA → driver は B→A → driver の左 = lateralOffset 正
			sp.lateralOffset = (nodeId == edge.nodeB) ? -lateralAbs : +lateralAbs;
			sp.poleHeight    = 2.5f;
			sp.autoGenerated = true;
			out << sp;
		}
		// 他のタイプは将来追加
	};

	if (edge.nodeA >= 0) checkNode(edge.nodeA);
	if (edge.nodeB >= 0) checkNode(edge.nodeB);

	return out;
}
