#pragma once
#include "RoadNetwork.hpp"
#include "RoadGeometry.hpp"

/// @brief 道路構造と交通制御から canonical な道路標示配置を生成する。
/// @details Renderer はここで生成した RoadMarkingPlacement をメッシュ化するだけにし、
///          横断歩道・停止線・車線線などの候補選別を一箇所へ集約する。
class RoadMarkingGenerator
{
public:
	struct Options
	{
		bool generateArterialLaneLines = true;
		bool generateEdgeCrosswalks = true;
		bool generateNodeMarkings = false;
	};

	static Array<RoadMarkingPlacement> collectEdge(const RoadNetwork& network, const RoadEdge& edge, const Options& options = Options{})
	{
		Array<RoadMarkingPlacement> placements;
		if (options.generateArterialLaneLines && edge.roadType == RoadType::Arterial && edge.isRoadbedBuilt())
		{
			appendSafeCenterLines(placements, network, edge);
		}

		if (options.generateEdgeCrosswalks && edge.roadType == RoadType::Arterial && edge.isRoadbedBuilt())
		{
			appendSafeEdgeCrosswalks(placements, network, edge);
		}

		appendManualMarkings(placements, network.manualMarkings(), RoadMarkingScope::Edge, edge.id);
		return placements;
	}

	static Array<RoadMarkingPlacement> collectNode(const RoadNetwork& network, int nodeId, bool isClose, const Options& options = Options{})
	{
		Array<RoadMarkingPlacement> placements;
		const RoadNode* node = network.getNode(nodeId);
		if (!node) return placements;

		if (node->attachments.size() == 2)
		{
			RoadMarkingPlacement seam;
			seam.kind = RoadMarkingKind::LaneLine;
			seam.scope = RoadMarkingScope::Node;
			seam.nodeId = nodeId;
			seam.autoGenerated = true;
			placements << seam;
		}

		if (options.generateNodeMarkings && isClose)
		{
			appendControlledStopLines(placements, network, nodeId, *node);
		}

		appendManualMarkings(placements, network.manualMarkings(), RoadMarkingScope::Node, nodeId);
		return placements;
	}

private:
	static bool markingTargetsEdge(const RoadMarkingPlacement& marking, int edgeId)
	{
		return marking.scope == RoadMarkingScope::Edge && marking.edgeId == edgeId;
	}

	static bool markingTargetsNode(const RoadMarkingPlacement& marking, int nodeId)
	{
		return marking.scope == RoadMarkingScope::Node && marking.nodeId == nodeId;
	}

	static void appendManualMarkings(Array<RoadMarkingPlacement>& placements,
	                                const Array<RoadMarkingPlacement>& manualMarkings,
	                                RoadMarkingScope scope, int targetId)
	{
		for (const RoadMarkingPlacement& marking : manualMarkings)
		{
			const bool matches = (scope == RoadMarkingScope::Edge)
				? markingTargetsEdge(marking, targetId)
				: markingTargetsNode(marking, targetId);
			if (!matches) continue;

			if (marking.overrideMode == RoadMarkingOverrideMode::Suppress
				|| marking.overrideMode == RoadMarkingOverrideMode::Replace)
			{
				placements.remove_if([&](const RoadMarkingPlacement& existing)
				{
					return existing.autoGenerated && existing.kind == marking.kind;
				});
			}
			if (marking.overrideMode != RoadMarkingOverrideMode::Suppress)
			{
				placements << marking;
			}
		}
	}

	static Vec2 edgeTangentAtNode(const RoadNetwork& network, const RoadEdge& edge, int nodeId)
	{
		const auto bezier = network.getBezier(edge.id);
		if (!bezier || bezier->totalLength <= 1.0f) return Vec2{ 0.0f, 0.0f };
		const bool isNodeA = (edge.nodeA == nodeId);
		const float cutoff = isNodeA ? edge.cutoffA : edge.cutoffB;
		const float arc = isNodeA
			? Clamp(cutoff + 3.0f, 0.0f, bezier->totalLength)
			: Clamp(bezier->totalLength - cutoff - 3.0f, 0.0f, bezier->totalLength);
		Vec3 tangent3 = bezier->tangentAt(arc);
		if (!isNodeA) tangent3 = -tangent3;
		Vec2 tangent{ static_cast<float>(tangent3.x), static_cast<float>(tangent3.z) };
		if (tangent.lengthSq() <= 1e-8f) return Vec2{ 0.0f, 0.0f };
		tangent.normalize();
		return tangent;
	}

	static bool hasNearlyOrthogonalCrossTraffic(const RoadNetwork& network, int nodeId, int targetEdgeId, const Vec2& targetTangent)
	{
		const RoadNode* node = network.getNode(nodeId);
		if (!node || node->attachments.size() < 3 || targetTangent.lengthSq() <= 1e-8f) return false;
		for (const EdgeAttachment& attachment : node->attachments)
		{
			if (attachment.edgeId == targetEdgeId) continue;
			const RoadEdge* other = network.getEdge(attachment.edgeId);
			if (!other || !other->isRoadbedBuilt()) continue;
			if (other->roadType != RoadType::LocalRoad && other->roadType != RoadType::Arterial) continue;
			const Vec2 otherTangent = edgeTangentAtNode(network, *other, nodeId);
			if (otherTangent.lengthSq() <= 1e-8f) continue;
			if (Abs(targetTangent.dot(otherTangent)) <= 0.28f) return true;
		}
		return false;
	}

	static void appendSafeCenterLines(Array<RoadMarkingPlacement>& placements, const RoadNetwork& network, const RoadEdge& edge)
	{
		const auto bezier = network.getBezier(edge.id);
		if (!bezier || edge.lanes.size() < 2) { return; }
		const float begin = Max(0.0f, edge.cutoffA - 0.1f);
		const float end = Min(bezier->totalLength, bezier->totalLength - edge.cutoffB + 0.1f);
		if (end - begin < 0.2f) { return; }
		HashSet<int> usedOffsets;
		for (const auto& lane : edge.lanes)
		{
			for (const auto boundary : { std::pair<float,LineType>{lane.offsetA_L,lane.lineLeft}, {lane.offsetA_R,lane.lineRight} })
			{
				if (boundary.second == LineType::None || !usedOffsets.insert(static_cast<int>(Round(boundary.first * 100))).second) { continue; }
				RoadMarkingPlacement line;
				line.kind = RoadMarkingKind::LaneLine;
				line.scope = RoadMarkingScope::Edge;
				line.edgeId = edge.id;
				line.arcOffset = begin;
				line.length = end - begin;
				line.lateralCenter = boundary.first;
				line.width = 0.15f;
				line.autoGenerated = true;
				placements << line;
			}
		}
	}
	static bool isStableCrosswalkArc(const CubicBezier& bezier, float arc)
	{
		const float before = Clamp(arc - 5.0f, 0.0f, bezier.totalLength);
		const float after = Clamp(arc + 5.0f, 0.0f, bezier.totalLength);
		Vec2 a{ static_cast<float>(bezier.tangentAt(before).x), static_cast<float>(bezier.tangentAt(before).z) };
		Vec2 b{ static_cast<float>(bezier.tangentAt(after).x), static_cast<float>(bezier.tangentAt(after).z) };
		if (a.lengthSq() <= 1e-8f || b.lengthSq() <= 1e-8f) return false;
		a.normalize();
		b.normalize();
		return a.dot(b) >= 0.992f;
	}

	static void appendSafeEdgeCrosswalks(Array<RoadMarkingPlacement>& placements, const RoadNetwork& network, const RoadEdge& edge)
	{
		const auto bezier = network.getBezier(edge.id);
		if (!bezier || bezier->totalLength <= 38.0f) return;

		for (const auto& nodeRef : { std::pair<int, bool>{ edge.nodeA, true }, std::pair<int, bool>{ edge.nodeB, false } })
		{
			const int nodeId = nodeRef.first;
			const RoadNode* node = network.getNode(nodeId);
			if (!node || node->attachments.size() < 3) continue;

			const Vec2 approachTangent = edgeTangentAtNode(network, edge, nodeId);
			if (approachTangent.lengthSq() <= 1e-8f) continue;
			const bool hasCrossTraffic = hasNearlyOrthogonalCrossTraffic(network, nodeId, edge.id, approachTangent);
			if (!hasCrossTraffic) continue;
			bool overlappingApproach = false;
			for (const auto& attachment : node->attachments)
			{
				const auto* other = network.getEdge(attachment.edgeId);
				if (other && other->id != edge.id && approachTangent.dot(edgeTangentAtNode(network,*other,nodeId)) > 0.80) { overlappingApproach = true; break; }
			}
			if (overlappingApproach) { continue; }

			const float cutoff = nodeRef.second ? edge.cutoffA : edge.cutoffB;
			const float arc = nodeRef.second
				? Clamp(cutoff + 3.0f, 0.0f, bezier->totalLength)
				: Clamp(bezier->totalLength - cutoff - 3.0f, 0.0f, bezier->totalLength);
			if (!isStableCrosswalkArc(*bezier, arc)) continue;

			const RoadGeometry::LateralRange roadbedRange = RoadGeometry::roadbedRangeAt(edge, arc / Max(1.0f, bezier->totalLength));
			if (!roadbedRange.valid || roadbedRange.width() <= 6.8f) continue;

			RoadMarkingPlacement crosswalk;
			crosswalk.kind = RoadMarkingKind::Crosswalk;
			crosswalk.scope = RoadMarkingScope::Edge;
			crosswalk.edgeId = edge.id;
			crosswalk.nodeEndId = nodeId;
			crosswalk.arcOffset = arc;
			crosswalk.lateralCenter = (roadbedRange.left + roadbedRange.right) * 0.5f;
			crosswalk.width = Clamp(roadbedRange.width() - 2.10f, 4.2f, 10.5f);
			crosswalk.length = 3.2f;
			crosswalk.autoGenerated = true;
			placements << crosswalk;
		}
	}

	static void appendControlledStopLines(Array<RoadMarkingPlacement>& placements, const RoadNetwork&, int nodeId, const RoadNode& node)
	{
		bool hasStopControl = false;
		for (const EdgeAttachment& attachment : node.attachments)
		{
			if (attachment.control == TrafficControl::Stop || attachment.control == TrafficControl::Signal)
			{
				hasStopControl = true;
				break;
			}
		}
		if (!hasStopControl) return;

		RoadMarkingPlacement stopLine;
		stopLine.kind = RoadMarkingKind::StopLine;
		stopLine.scope = RoadMarkingScope::Node;
		stopLine.nodeId = nodeId;
		stopLine.autoGenerated = true;
		placements << stopLine;
	}
};
