#pragma once
#include "../time/GameClock.hpp"
#include "RoadEnums.hpp"
#include "RoadPartTypes.hpp"
#include "BezierUtil.hpp"

// ===== 高架関連定数 =====

/// @brief 路面リフト（地形高さから路面までのオフセット）[m]
constexpr double kRoadSurfaceLift     = 2.0;
/// @brief 路面ライン描画用リフト（路面よりわずかに上）[m]
constexpr double kRoadLineLift        = 2.05;
/// @brief 高架自動判定の閾値（ノードYと地形高の差）[m]
constexpr double kElevationThreshold  = 0.5;

// ===== 列挙型 =====

/// @brief 運用状態: 現在の交通への供用状態（頻繁に変化）
enum class OpState : uint8
{
	Open,        ///< 供用中
	Provisional, ///< 暫定供用
	Closed,      ///< 閉鎖
	Reserved,    ///< 将来供用のため確保
};

/// @brief 向き
enum class LaneDir : uint8
{
	Forward,   ///< A → B
	Backward,  ///< B → A
};

/// @brief 機能種別
enum class LaneType : uint8
{
	Normal,
	Overtaking,
	Acceleration,
	Deceleration,
	TurnLeft,
	TurnRight,
	Bus,
	ParkingBay,
	EmergencyStop,
	KeepOut,        ///< 立入り禁止部分（規制標示101・ゼブラゾーン）
	TrafficIsland,  ///< 導流帯（指示標示208の2・分岐合流鼻の縞模様）
};

/// @brief 区画線種別
enum class LineType : uint8
{
	None,           ///< 線なし
	SolidWhite,     ///< 白実線（車線変更禁止）
	DashedWhite,    ///< 白破線（車線変更可）
	SolidYellow,    ///< 黄実線（追い越し禁止）
	DoubleYellow,   ///< 黄二重線
};

/// @brief ノード種別
enum class NodeType : uint8
{
	Endpoint,      ///< 端点（1本接続）
	Joint,         ///< 継ぎ目（2本接続）
	Intersection,  ///< 交差点（3本以上、isThrough なし）
	Diverge,       ///< 分岐合流（3本以上、isThrough 2本）
};

/// @brief ノードでの遷移方式（Joint 時のみ有効）
/// @details 17_road_node_spec.md 参照
enum class NodeTransition : uint8
{
	Blend,    ///< 部品を滑らかにモーフィング（車線減少・幅変化）
	Abrupt,   ///< ノード中心で不連続に切替（延伸端・道路種別境界）
};

/// @brief エッジ単位の交通規制
enum class TrafficControl : uint8
{
	None,    ///< 規制なし（減速せず通過）
	Yield,   ///< 譲れ（非優先道路側: 交差車両がいれば減速/停止）
	Stop,    ///< 一時停止（必ず一旦停止してから発進）
	Signal,  ///< 信号機制御
};

/// @brief エッジのノードへの接続情報
/// @details 17_road_node_spec.md 参照
struct EdgeAttachment
{
	int   edgeId = -1;
	float lateralOffset = 0.0f;  ///< ノード中心からの横方向オフセット [m]（エッジ外向き接線に対して右が正）
	bool  isThrough = false;     ///< Diverge ノード専用: 本線エッジなら true
	TrafficControl control = TrafficControl::None;  ///< この方向の交通規制
};

/// @brief 道路種別
enum class RoadType : uint8
{
	LocalRoad,    ///< 一般道（市道・町道）
	Arterial,     ///< 幹線道路（国道・県道）
	Expressway,   ///< 高速道路（自動車専用道）
	Highway,      ///< 有料道路
};

/// @brief エッジ状態
enum class EdgeState : uint8
{
	Existing,
	Planned,
	UnderConstruction,
	Open,
	Closed,
};

/// @brief 道路計画の状態
enum class PlanState : uint8
{
	Planning,
	Approved,
	UnderConstruction,
	Complete,
};

// ===== RoadSign（標識） =====

/// @brief 道交法上の標識分類
/// @details 道路標識、区画線及び道路標示に関する命令（昭和35年総理府建設省令3号）に準拠。
enum class RoadSignCategory : uint8
{
	Regulatory,   ///< 規制標識（赤円・逆三角 等／禁止・規制）
	Warning,      ///< 警戒標識（黄ひし形／危険予告）
	Instruction,  ///< 指示標識（青角丸四角／通行方法の指示）
	Guide,        ///< 案内標識（緑/青長方形・おにぎり／方面案内）
	Auxiliary,    ///< 補助標識（白長方形／本標識の補足）
};

/// @brief 道路標識の種別
/// @details 詳細は plan/07_road_lane_spec.md §11、API は RoadSign.hpp 参照。
///   各種別は RoadSign::visualOf(type) で (category, 形状OBJ, テクスチャ) に解決される。
enum class RoadSignType : uint8
{
	None,
	Stop,           ///< 一時停止（規制・逆三角・330）
	Yield,          ///< 徐行（規制・逆三角・329）
	SpeedLimit,               ///< 最高速度（規制・赤円・323）(将来)
	NoEntry,                  ///< 車両進入禁止（規制・赤円・303）
	OneWay,                   ///< 一方通行（指示・青矩形・326）(将来)
	NationalRoute,            ///< 一般国道標識（案内・おにぎり・118）— route 由来の動的生成
	DirectionalRestriction,   ///< 指定方向外進行禁止（規制・青円・311）
};

/// @brief 道路標識の配置情報（RoadEdge.signs に格納）
struct RoadSignPlacement
{
	RoadSignType type          = RoadSignType::None;
	int          nodeEndId     = -1;     ///< edge.nodeA か edge.nodeB のどちらか
	float        arcOffset     = 0.0f;   ///< nodeEnd 端からの追加弧長 [m]（0=cutoff 位置）
	float        lateralOffset = 0.0f;   ///< 道路中心からの横方向 [m]（負=左 in A→B 方向）
	float        poleHeight    = 2.5f;   ///< ポール高さ [m]
	float        yawOffset     = 0.0f;   ///< 看板の向き調整 [rad]
	int          auxValue      = 0;      ///< SpeedLimit の速度値など
	bool         autoGenerated = true;   ///< 自動生成エントリか手動配置か
};

// ===== GuideSign（案内標識: 方面系） =====

/// @brief 案内標識の種別（方面系）
/// @details 詳細は plan/21_guide_sign_spec.md
enum class GuideSignKind : uint8
{
	DirectionDistance,   ///< 106: 矢印 + (地名, 距離km) × 1〜3
	DirectionArrow,      ///< 108の2: (地名, 方向矢印) × 2〜3（交差点手前・Phase2）
};

/// @brief 看板要素の種別
enum class SignElementKind : uint8
{
	Text,         ///< テキスト（地名 + ローマ字）
	Arrow,        ///< 矢印（回転角度で方向指定）
	ArrowNoHead,  ///< 矢頭なし矢印シャフト（丁字路の直進軸に使用）
	RouteNumber,  ///< 国道番号アイコン（おにぎり型テクスチャ＋番号）value に番号を格納
	DestName,     ///< 地名＋読み（左寄せ）
	DestDistance, ///< 距離数字のみ表示、地名は参照保持
};

struct SignElement
{
	SignElementKind kind  = SignElementKind::Text;
	float posX   = 0.5f;  ///< 正規化 X 座標 [0-1]（盤面左端=0, 右端=1）
	float posY   = 0.5f;  ///< 正規化 Y 座標 [0-1]（盤面上端=0, 下端=1）
	// Text 用
	float scale  = 1.0f;  ///< フォントサイズ倍率（1.0 = デフォルト）
	String text;           ///< 表示テキスト（地名等）
	String reading;        ///< ローマ字（空なら非表示）
	// Arrow 用
	float arrowAngle  = 0.0f;  ///< 矢印回転角 [度]（0=↑, 任意角度可）
	float arrowLength = 0.0f;  ///< 矢印全長 [px]（始点から矢頭先端まで）
	float value       = 0.0f;  ///< DestDistance: km 値
};

/// @brief 案内標識配置情報（RoadNetwork::m_guideSigns で集中管理、id で紐付け）
struct GuideSignPlacement
{
	int                   id            = -1;    ///< ネットワーク内で一意の ID
	int                   parentEdgeId  = -1;    ///< 親エッジ ID（エッジ削除時に連動）
	GuideSignKind         kind          = GuideSignKind::DirectionDistance;
	int                   nodeEndId     = -1;    ///< 進行方向基準ノード
	float                 arcOffset     = 0.0f;  ///< nodeEnd 端からの内側距離 [m]
	float                 lateralOffset = 0.0f;  ///< 道路中心からの横方向 [m]
	float                 poleHeight    = 3.5f;  ///< ポール高さ [m]（現在は guide_pole.json の値で上書き、UI 非編集）
	bool                  autoGenerated = true;  ///< 自動推論 / 手動上書き
	int                   sourceNodeId  = -1;    ///< 自動生成の起点交差点ノードID（手動配置は -1）

	// ── 自由度フィールド（上書き。0/空 = 自動計算 / デフォルト使用）──
	float                 widthOverride  = 0.0f; ///< 板幅 [m]（0=自動）
	float                 heightOverride = 0.0f; ///< 板高 [m]（0=自動）
	ColorF                bgColor       { 0.0, 0.0 }; ///< 背景色（alpha=0 でデフォルト青を使用）
	bool                  showReading   = true;  ///< 下段にローマ字を表示するか

	/// @brief 看板要素（自由配置）。InferAutoForEdge も含めて常にここから描画する。
	Array<SignElement>    elements;
};

// ===== RoadRoute（道路路線） =====

/// @brief 道路路線の種別
/// @details 詳細は plan/22_road_route_spec.md 参照
enum class RoadRouteKind : uint8
{
	Expressway,       ///< 高速自動車国道 (例: 中央自動車道)
	NationalRoute,    ///< 一般国道 (例: 国道19号)
	PrefectureRoute,  ///< 都道府県道 (例: 県道100号)
	CityRoute,        ///< 市町村道
	Named,            ///< 通称 (例: 青山通り)
};

/// @brief 道路路線データ
/// @details 複数の RoadEdge を順序付きで束ねる。1 エッジが複数 route に所属可。
struct RoadRoute
{
	int              id         = -1;
	RoadRouteKind    kind       = RoadRouteKind::Named;
	String           name;                 ///< 正式名称 ("国道19号" 等)
	int              number     = 0;       ///< 番号 (1〜400, 0=無番号)
	Array<int>       edgeIds;               ///< 構成エッジ (起点→終点)
	ColorF           color{ 0.5 };          ///< 表示色
};

// ===== Lane =====

/// @brief 車線データ
struct Lane
{
	// --- 幾何（A端・B端で異なる位置 → テーパー車線対応） ---
	float   offsetA_L = 0.0f;              ///< A端: 道路中心からの左端 [m]
	float   offsetA_R = 0.0f;              ///< A端: 道路中心からの右端 [m]
	float   offsetB_L = 0.0f;              ///< B端: 道路中心からの左端 [m]
	float   offsetB_R = 0.0f;              ///< B端: 道路中心からの右端 [m]

	// --- 運用 ---
	LaneDir   dir = LaneDir::Forward;      ///< 走行方向
	OpState   op  = OpState::Open;         ///< 供用状態

	// --- 車線変更 ---
	bool      canChangeLaneLeft  = false;  ///< 左隣の車線への変更が可能か
	bool      canChangeLaneRight = false;  ///< 右隣の車線への変更が可能か

	// --- 区画線 ---
	LineType  lineLeft  = LineType::None;  ///< 左側の区画線種別
	LineType  lineRight = LineType::None;  ///< 右側の区画線種別

	// --- ゲームプレイ ---
	float     nominalWidth = 3.5f;         ///< 公称幅 [m]（容量計算・UI表示用）
	LaneType  type = LaneType::Normal;     ///< 機能種別

	/// @brief A端・B端の中心オフセットを弧長割合 ft で補間した値を返す
	/// @param ft  0.0 = A端, 1.0 = B端（bez.totalLength > 0 なら arc / totalLength）
	/// @return 道路中心からの横方向オフセット [m]（右が正）
	float centerAt(float ft) const
	{
		const float cA = (offsetA_L + offsetA_R) * 0.5f;
		const float cB = (offsetB_L + offsetB_R) * 0.5f;
		return cA + (cB - cA) * ft;
	}
};


// ===== TempOp =====

/// @brief TempOp による個別車線の運用上書き
struct LaneOpOverride
{
	int     laneIndex;
	LaneDir newDir;
	OpState newOp;
};

/// @brief 一時的な運用変更の種別
enum class TempOpKind : uint8
{
	Construction,   ///< 工事（CrossingClose > Construction > Event の優先度）
	CrossingClose,  ///< 踏切閉鎖
	Event,          ///< 祭り・交通規制など
};

/// @brief 一時的な運用変更
struct TempOp
{
	TempOpKind            kind;
	Array<LaneOpOverride> overrides;
	GameTime              start = 0.0;
	GameTime              end   = 0.0;
	String                reason;
};

// ===== PlannedChange =====

/// @brief 将来の計画的変化における部品の変更仕様
struct PartChange
{
	int                  partIndex;
	Optional<BuildState> newBuild;
};

/// @brief 将来の計画的変化における車線の変更仕様
struct LaneChange
{
	int                  laneIndex;
	Optional<LaneDir>    newDir;
	Optional<OpState>    newOp;
};

/// @brief PlannedChange の発動トリガー
enum class Trigger : uint8
{
	OnConstruction,
	OnOpen,
};

/// @brief 将来の計画的変化
struct PlannedChange
{
	int                planId;
	Trigger            trigger;
	Array<PartChange>  partChanges;
	Array<LaneChange>  laneChanges;
};

// ===== RoadEdge =====

/// @brief 道路エッジ（ベジェ曲線の道路区間）
struct RoadEdge
{
	int       id       = -1;
	int       nodeA    = -1;
	int       nodeB    = -1;
	Vec3      ctrlA;                          ///< ベジェ制御点A
	Vec3      ctrlB;                          ///< ベジェ制御点B
	RoadType  roadType  = RoadType::LocalRoad;
	float     speedLimit = 60.0f;            ///< 制限速度 [km/h]
	float     length     = 0.0f;            ///< 弧長 [m]
	int       planId     = -1;              ///< 所属 RoadPlan（-1 = 既存道路）

	/// @brief nodeA 端でのカットオフ量 [m]（描画メッシュをノード手前で切る距離）
	/// @note RoadNetwork::updateNodeCutoffs() で自動計算される。0 = カットなし（端点）
	float     cutoffA   = 0.0f;
	/// @brief nodeB 端でのカットオフ量 [m]
	float     cutoffB   = 0.0f;

	/// @brief 物理構造（道路部品の配列、左端から右端の順）
	Array<RoadPart>      parts;

	Array<Lane>          lanes;
	Array<TempOp>        tempOps;
	Array<PlannedChange> planned;
	Array<Array<int>>    laneVehicles;      ///< 車線ごとの vehicleId リスト
	Array<RoadSignPlacement> signs;         ///< 標識配置（plan/07_road_lane_spec.md §11）
	/// @note 案内標識（GuideSignPlacement）は RoadNetwork::m_guideSigns で集中管理し、
	///   parentEdgeId で紐付ける（plan/21_guide_sign_spec.md）

	/// @brief このエッジが所属する RoadRoute の ID 列（逆引きキャッシュ）
	/// @details 永続化しない。ロード時に RoadNetwork::rebuildEdgeRouteIndex() で再構築される。
	///   canonical は RoadRoute::edgeIds。plan/22_road_route_spec.md §1 参照。
	Array<int>           routeIds;

	EdgeState edgeState = EdgeState::Open;
	float     congestion = 0.0f;

	bool      useElevation = false;  ///< true: ベジェ Y を路面高さとして使用（高架）

	// 経路探索サポート（Phase 2 で使用）
	int borderNodeA = -1;
	int borderNodeB = -1;

	/// @brief TempOp を適用した有効な車線状態を返す
	/// @param i     車線インデックス
	/// @param now   現在のゲーム時刻
	Lane effectiveLane(int i, GameTime now) const
	{
		Lane L = lanes[i];
		// 優先度順にソート: CrossingClose < Construction < Event（値が小さいほど優先）
		auto ops = tempOps;
		ops.sort_by([](const TempOp& a, const TempOp& b)
		{
			// CrossingClose=1 > Construction=0 > Event=2
			// 優先度: CrossingClose > Construction > Event
			const auto priority = [](TempOpKind k) -> int
			{
				switch (k)
				{
				case TempOpKind::CrossingClose: return 0;
				case TempOpKind::Construction:  return 1;
				case TempOpKind::Event:         return 2;
				}
				return 3;
			};
			return priority(a.kind) < priority(b.kind);
		});
		for (const auto& op : ops)
		{
			if (op.start <= now && now <= op.end)
			{
				for (const auto& ov : op.overrides)
				{
					if (ov.laneIndex == i)
					{
						L.dir = ov.newDir;
						L.op  = ov.newOp;
					}
				}
			}
		}
		return L;
	}

	/// @brief 指定方向の走行可能な車線インデックス一覧を返す
	Array<int> openLanes(LaneDir dir, GameTime now) const
	{
		Array<int> result;
		for (int i = 0; i < static_cast<int>(lanes.size()); ++i)
		{
			const Lane L = effectiveLane(i, now);
			if (isRoadbedBuilt() && (L.op == OpState::Open || L.op == OpState::Provisional) && L.dir == dir)
				result << i;
		}
		return result;
	}

	/// @brief 道路の総幅を返す [m]（parts ベース）
	float totalWidth() const
	{
		float minOff = 1e9f, maxOff = -1e9f;
		for (const auto& p : parts)
		{
			minOff = Min(minOff, p.offset);
			maxOff = Max(maxOff, p.offset + p.width);
		}
		return (minOff < maxOff) ? (maxOff - minOff) : 0.0f;
	}

	/// @brief 路盤パーツが建設済みかどうか
	[[nodiscard]]
	bool isRoadbedBuilt() const
	{
		for (const auto& part : parts)
		{
			if (part.type == RoadPartType::Roadbed && part.build == BuildState::Built)
				return true;
		}
		return false;
	}
};

/// @brief 車線が走行可能か（新シグネチャ: RoadEdge + 車線インデックス）
/// @details 路盤パーツの BuildState + 車線の OpState で判定
inline bool isPassable(const RoadEdge& edge, int laneIndex)
{
	if (laneIndex < 0 || laneIndex >= static_cast<int>(edge.lanes.size()))
		return false;
	const auto& lane = edge.lanes[laneIndex];
	return edge.isRoadbedBuilt()
		&& (lane.op == OpState::Open || lane.op == OpState::Provisional);
}

// ===== LaneConnection =====

/// @brief 交差点内の車線接続（旋回パス）
/// @details 19_vehicle_movement_spec.md 参照
struct LaneConnection
{
	int         id            = -1;
	int         fromEdgeId    = -1;
	int         fromLaneIndex = 0;
	int         toEdgeId      = -1;
	int         toLaneIndex   = 0;
	CubicBezier path;              ///< 交差点内の旋回ベジェ曲線
};

// ===== 信号配置 =====

/// @brief 信号フェーズ（永続化用）
struct SignalPhaseDef
{
	float      duration = 30.0f;   ///< フェーズ持続時間 [ゲーム秒]
	Array<int> greenConnectionIds; ///< このフェーズで青になる LaneConnection の ID リスト
};

/// @brief ノードに設置された信号機の配置情報
struct SignalPlacement
{
	String signalDefId;          ///< SignalRegistry の定義 ID
	float yawOffset = 0.0f;      ///< Y 軸回転オフセット [rad]
	/// @brief ユーザー定義の信号フェーズ（空なら自動生成）
	Array<SignalPhaseDef> phases;
};

// ===== RoadNode =====

/// @brief 道路ノード（端点・継ぎ目・交差点・分岐合流）
/// @details 17_road_node_spec.md 参照
struct RoadNode
{
	int                    id = -1;
	Vec3                   position;
	NodeType               type       = NodeType::Endpoint;
	NodeTransition         transition = NodeTransition::Blend;
	Array<EdgeAttachment>  attachments;
	Array<LaneConnection>  laneConnections;  ///< 交差点の車線接続リスト
	int                    nextConnectionId = 0;

	/// @brief 信号機の配置情報（none = 信号なし）
	Optional<SignalPlacement> signalPlacement;

	/// @brief 接続エッジ ID 一覧を返す（旧 edgeIds 互換）
	[[nodiscard]] Array<int> edgeIds() const
	{
		Array<int> ids;
		ids.reserve(attachments.size());
		for (const auto& a : attachments) ids << a.edgeId;
		return ids;
	}

	/// @brief エッジを追加する
	void addEdge(int edgeId)
	{
		attachments << EdgeAttachment{ edgeId };
	}

	/// @brief エッジを削除する
	void removeEdge(int edgeId)
	{
		attachments.remove_if([edgeId](const EdgeAttachment& a) { return a.edgeId == edgeId; });
	}

	/// @brief 指定エッジの接続情報を取得する（なければ nullptr）
	[[nodiscard]] EdgeAttachment* getAttachment(int edgeId)
	{
		for (auto& a : attachments)
			if (a.edgeId == edgeId) return &a;
		return nullptr;
	}
	[[nodiscard]] const EdgeAttachment* getAttachment(int edgeId) const
	{
		for (const auto& a : attachments)
			if (a.edgeId == edgeId) return &a;
		return nullptr;
	}
};

// ===== RoadPlan =====

/// @brief 道路計画
struct RoadPlan
{
	int        id = -1;
	String     name;
	String     originName;
	String     destName;
	RoadType   roadType  = RoadType::LocalRoad;
	Array<int> edgeIds;
	float      totalCost   = 0.0f;
	float      totalLength = 0.0f;         ///< 総延長 [km]
	PlanState  state = PlanState::Planning;

	Optional<GameTime> constructionStart;
	Optional<GameTime> completionDate;
};
