#include "GuideSignEditor.hpp"
#include "../road/RoadNetwork.hpp"
#include "../road/GuideSign.hpp"
#include "../road/RoadSign.hpp"
#include "../render/RoadRenderer.hpp"
#include "../ui/PanelManager.hpp"
#include "../ui/PanelLayout.hpp"
#include "../asset/AssetRegistrar.hpp"

namespace
{
	constexpr StringView kKindNames[] = { U"方面及び距離", U"方面及び方向" };

	/// @brief 看板エディタパネルの初期オープン時サイズ [px]
	constexpr Vec2 kEditorPanelInitialSize{ 500.0, 600.0 };

	/// @brief 選択ハイライトの外枠色
	constexpr ColorF kSelectionHighlightColor{ 1.0, 1.0, 0.0, 0.8 };
	/// @brief 選択ハイライトの外枠太さ
	constexpr double kSelectionHighlightThickness = 1.5;

	/// @brief プレビュー内のクリックヒット半径（px）二乗
	constexpr double kClickHitRadiusSq = 1600.0;  // 40px 半径

	/// @brief 矢印キーでの移動量（Shift なし / Shift ありの 1 フレーム当たり px）
	constexpr float  kArrowKeyStepPx       = 1.0f;
	constexpr float  kArrowKeyShiftStepPx  = 10.0f;

	/// @brief ホイール回転ステップ [度]
	constexpr float  kArrowWheelRotateDeg  = 15.0f;

	/// @brief 指定種別に応じた新規 SignElement を生成する
	SignElement createNewElement(SignElementKind kind)
	{
		SignElement el;
		el.kind = kind;
		el.posX = 0.5f;
		el.posY = 0.5f;
		switch (kind)
		{
		case SignElementKind::Text:
			el.text = U"地名";
			break;
		case SignElementKind::DestName:
			el.scale = 0.08f;
			el.text  = U"地名";
			break;
		case SignElementKind::DestDistance:
			el.scale = 0.08f;
			el.value = 10.0f;
			break;
		case SignElementKind::Arrow:
		default:
			break;
		}
		return el;
	}

	/// @brief 配置パラメータ (弧長 / 横) を1行で表示
	/// @details ポール高と看板位置はポール OBJ の JSON で定義する
	bool drawPlacementRow(PanelBuilder& ui, GuideSignPlacement& g)
	{
		bool changed = false;
		ui.row(3, [&] {
			ui.label(U"弧長:", ColorF{ 0.5 });
			if (ui.numberInput(g.arcOffset, 10.0f, 0.0f, 2000.0f, U"{:.0f}", 45))
			{ g.autoGenerated = false; changed = true; }
			ui.label(U"横:", ColorF{ 0.5 });
			if (ui.numberInput(g.lateralOffset, 0.5f, -20.0f, 20.0f, U"{:.1f}", 40))
			{ g.autoGenerated = false; changed = true; }
		});
		return changed;
	}

	/// @brief パネル幅に合わせて縮小したプレビューを描画
	/// @param panelId プレビューを描画するパネル ID（パネル幅取得用）
	/// @param originX 描画開始 X 座標
	/// @return 描画領域 { width, height } (未描画時 {0,0})
	Vec2 drawPreview(PanelBuilder& ui, const GuideSignPlacement& g,
	                 const RoadRenderer& renderer, const PanelManager& pm,
	                 StringView panelId, double originX)
	{
		const Texture* cachedTex = renderer.getGuideSignCachedTexture(g);
		if (!cachedTex || !(*cachedTex))
		{
			ui.label(U"(テクスチャ未生成)", ColorF{ 0.5 });
			return Vec2{ 0, 0 };
		}
		const int panelW = static_cast<int>(pm.getSize(panelId).x) - 16;
		const double scale  = Min(1.0, static_cast<double>(panelW) / cachedTex->width());
		const int    drawH  = Max(20, static_cast<int>(cachedTex->height() * scale));
		const double drawW  = cachedTex->width() * scale;
		const double drawY  = static_cast<double>(ui.height());
		cachedTex->scaled(scale).draw(originX, drawY);
		return Vec2{ drawW, static_cast<double>(drawH) };
	}

}

// =============================================================================
// 公開 API: open / close
// =============================================================================

void GuideSignEditor::open(int signId, [[maybe_unused]] const RoadNetwork& network)
{
	m_editingSignId = signId;
}

void GuideSignEditor::close()
{
	m_editingSignId      = -1;
	m_selectedElement    = -1;
	m_dragging           = false;
	m_copyDrag           = false;
	m_draftElements.clear();
	m_draftValid         = false;
	m_draftTex           = RenderTexture{};
	m_draftTexDirty      = true;
	m_lastSelectedElement = -1;
}

// =============================================================================
// エッジパネル内セクション
// =============================================================================

bool GuideSignEditor::drawEdgeSection(PanelBuilder& ui, RoadEdge& edge,
                                      RoadNetwork& network, PanelManager& panelManager,
                                      const RoadRenderer& renderer)
{
	bool dirty = false;

	Array<int> myIds;
	for (const auto& g : network.guideSigns())
		if (g.id >= 0 && g.parentEdgeId == edge.id) myIds << g.id;

	static bool collapsed = true;
	ui.spacer(3);
	if (!ui.section(U"案内標識 ({})"_fmt(myIds.size()), collapsed, ColorF{ 0.7, 0.9, 1.0 }))
		return false;

	int deleteSignId = -1;

	for (const int signId : myIds)
	{
		GuideSignPlacement* gp = network.getGuideSign(signId);
		if (!gp) continue;
		auto& g = *gp;

		// 種別 + 編集 + 削除
		ui.row(3, [&] {
			if (ui.cycle(g.kind, kKindNames, 2, 100, U"種別を切替"))
			{ g.autoGenerated = false; dirty = true; }
			if (ui.button(U"編集", false, 40, U"エディタを開く"))
			{
				open(signId, network);
				panelManager.show(U"guide_sign_edit",
					U"案内標識 #{}"_fmt(signId), Vec2{ 20, 100 });
			}
			if (ui.button(U"削", false, 28)) deleteSignId = signId;
		});

		// 配置パラメータ
		if (drawPlacementRow(ui, g)) dirty = true;

		// プレビュー
		const Vec2 pv = drawPreview(ui, g, renderer, panelManager, U"edge_info", 8.0);
		if (pv.y > 0) ui.spacer(static_cast<int>(pv.y) + 2);
		ui.spacer(3);
	}

	// 新規追加ボタン
	const auto rb = RoadSign::roadbedExtentsOf(edge);
	const float leftLat  = rb.left  - GuideSign::kSideMargin_m;
	const float rightLat = rb.right + GuideSign::kSideMargin_m;
	const auto addSign = [&](int nodeId, float lat, GuideSignKind kind) {
		GuideSignPlacement gp;
		gp.parentEdgeId  = edge.id; gp.kind = kind; gp.nodeEndId = nodeId;
		gp.arcOffset     = (kind == GuideSignKind::DirectionArrow)
			? Min(GuideSign::kArrowPlaceArcOffset_m, edge.length * 0.7f)
			: GuideSign::kAutoPlaceArcOffset_m;
		gp.lateralOffset = lat;
		gp.poleHeight    = GuideSign::kPoleHeight_m;
		gp.autoGenerated = false;
		// elements は空のまま追加 → 編集パネルから看板エディタで要素を追加する
		network.addGuideSign(gp);
	};
	if (edge.nodeA >= 0)
	{
		ui.row(3, [&] {
			ui.label(U"A端:", ColorF{ 0.5 });
			if (ui.button(U"+距離", false, 50)) { addSign(edge.nodeA, leftLat, GuideSignKind::DirectionDistance); dirty = true; }
			if (ui.button(U"+方向", false, 50)) { addSign(edge.nodeA, leftLat, GuideSignKind::DirectionArrow); dirty = true; }
		});
	}
	if (edge.nodeB >= 0)
	{
		ui.row(3, [&] {
			ui.label(U"B端:", ColorF{ 0.5 });
			if (ui.button(U"+距離", false, 50)) { addSign(edge.nodeB, rightLat, GuideSignKind::DirectionDistance); dirty = true; }
			if (ui.button(U"+方向", false, 50)) { addSign(edge.nodeB, rightLat, GuideSignKind::DirectionArrow); dirty = true; }
		});
	}

	if (deleteSignId >= 0) { network.removeGuideSign(deleteSignId); dirty = true; }
	return dirty;
}

// =============================================================================
// 看板プロパティパネル
// =============================================================================

bool GuideSignEditor::drawEditPanel(RoadNetwork& network, PanelManager& panelManager,
                                     const RoadRenderer& renderer)
{
	if (m_editingSignId < 0) { panelManager.hide(U"guide_sign_edit"); return false; }
	GuideSignPlacement* gp = network.getGuideSign(m_editingSignId);
	if (!gp) { close(); panelManager.hide(U"guide_sign_edit"); return false; }
	auto& g = *gp;

	auto area = panelManager.beginContent(U"guide_sign_edit");
	if (!area) return false;

	PanelBuilder ui(static_cast<int>(panelManager.getSize(U"guide_sign_edit").x));
	bool dirty = false;

	// 種別
	ui.row(4, [&] {
		ui.label(U"種別:", ColorF{ 0.6 });
		if (ui.cycle(g.kind, kKindNames, 2, 130))
		{ g.autoGenerated = false; dirty = true; }
	});

	// 配置パラメータ
	if (drawPlacementRow(ui, g)) dirty = true;

	// プレビュー
	ui.spacer(4);
	const Vec2 pv = drawPreview(ui, g, renderer, panelManager, U"guide_sign_edit", 8.0);
	if (pv.y > 0) ui.spacer(static_cast<int>(pv.y) + 4);

	// 削除 / 編集ボタン
	ui.spacer(2);
	bool deleteRequested = false;
	ui.row(2, [&] {
		if (ui.button(U"削除", false, 60, U"この案内標識を削除"))
			deleteRequested = true;
	});
	if (deleteRequested)
	{
		network.removeGuideSign(m_editingSignId);
		close();
		panelManager.hide(U"guide_sign_editor");
		panelManager.hide(U"guide_sign_edit");
		ui.flush();
		panelManager.reportContentHeight(U"guide_sign_edit", ui.height());
		return true;
	}

	ui.spacer(2);
	if (ui.button(U"編集", false, 60, U"看板エディタを開く"))
	{
		m_draftElements      = g.elements;  // 空の場合はブランクキャンバスで開始
		m_draftValid         = true;
		m_selectedElement    = -1;
		m_draftTexDirty      = true;
		m_lastSelectedElement = -1;

		const Vec2 center{
			(Scene::Width()  - kEditorPanelInitialSize.x) * 0.5,
			(Scene::Height() - kEditorPanelInitialSize.y) * 0.5 };
		panelManager.show(U"guide_sign_editor",
			U"看板エディタ #{}"_fmt(m_editingSignId), center);
	}

	ui.flush();
	panelManager.reportContentHeight(U"guide_sign_edit", ui.height());
	return dirty;
}

// =============================================================================
// WYSIWYG エディタパネル
// =============================================================================

void GuideSignEditor::regenerateDraftTextureIfDirty(const GuideSignPlacement& g)
{
	if (!m_draftValid || !m_draftTexDirty) return;

	const Font& fontJa  = FontAsset(Asset::CJK32Bold);
	const Font& fontNum = FontAsset(Asset::Arial24);
	if (!fontJa || !fontNum) return;

	GuideSignPlacement tmp = g;
	tmp.elements = m_draftElements;
	const auto   bs    = GuideSign::computeBoardSizeFor(tmp);
	const Size   ts    = GuideSign::guideSignTexSize(bs.width, bs.height);
	const ColorF bgCol = GuideSign::resolveBgColor(tmp.bgColor);

	RenderTexture rt{ static_cast<uint32>(ts.x), static_cast<uint32>(ts.y), bgCol };
	{
		const ScopedRenderTarget2D target{ rt };
		const ScopedRenderStates2D blend{ BlendState::Default2D };
		GuideSign::renderContents(tmp, ts, fontJa, fontNum);
		Graphics2D::Flush();
	}
	rt.generateMips();
	m_draftTex      = std::move(rt);
	m_draftTexDirty = false;
}

void GuideSignEditor::addElementFromToolbar(SignElementKind kind)
{
	m_draftElements << createNewElement(kind);
	m_selectedElement = static_cast<int>(m_draftElements.size()) - 1;
	m_draftTexDirty   = true;
}

void GuideSignEditor::deleteSelectedElement()
{
	if (!isDraftSelValid()) return;
	m_draftElements.erase(m_draftElements.begin() + m_selectedElement);
	m_selectedElement = -1;
	m_draftTexDirty   = true;
}

bool GuideSignEditor::drawEditorPanel(RoadNetwork& network, PanelManager& panelManager,
                                      [[maybe_unused]] const RoadRenderer& renderer)
{
	if (m_editingSignId < 0) { panelManager.hide(U"guide_sign_editor"); return false; }
	GuideSignPlacement* gp = network.getGuideSign(m_editingSignId);
	if (!gp) { panelManager.hide(U"guide_sign_editor"); return false; }
	auto& g = *gp;

	// ── draft テクスチャ生成（beginContent の前 = パネル座標変換なし）──
	regenerateDraftTextureIfDirty(g);

	auto area = panelManager.beginContent(U"guide_sign_editor");
	if (!area) return false;
	if (!m_draftValid) return false;  // 編集ボタンを経由しないと draft は無い

	PanelBuilder ui(static_cast<int>(panelManager.getSize(U"guide_sign_editor").x));
	// 看板エディタ内の編集は deferred-save: 全ての編集は draft に蓄積し、
	// 「保存して閉じる」クリック時に g.elements へ書き戻す（= キャッシュ invalidate）。
	bool dirty = false;
	bool closeRequested = false;
	Array<SignElement>& els = m_draftElements;

	// ── ツールバー ──
	ui.row(3, [&] {
		if (ui.button(U"保存して閉じる", false, 120, U"変更を反映してパネルを閉じる"))
		{
			closeRequested = true;
			dirty = true;
		}
		if (ui.button(U"リセット", false, 60, U"自動生成内容に戻す"))
		{
			const RoadEdge* edge = network.getEdge(g.parentEdgeId);
			if (edge)
			{
				const auto autos = GuideSign::InferAutoForEdge(*edge, network);
				for (const auto& a : autos)
					if (a.kind == g.kind && a.nodeEndId == g.nodeEndId)
					{ els = a.elements; break; }
			}
			else els.clear();
			m_selectedElement = -1;
			m_draftTexDirty = true;
		}
		if (ui.button(U"+テキスト", false, 75)) addElementFromToolbar(SignElementKind::Text);
		if (ui.button(U"+地名",     false, 55)) addElementFromToolbar(SignElementKind::DestName);
		if (ui.button(U"+距離",     false, 55)) addElementFromToolbar(SignElementKind::DestDistance);
		if (ui.button(U"+矢印",     false, 55)) addElementFromToolbar(SignElementKind::Arrow);
		if (isDraftSelValid() && ui.button(U"Del", false, 35))
		{
			deleteSelectedElement();
		}
	});

	// ── 整列 ──
	ui.row(2, [&] {
		ui.label(U"整列:", ColorF{ 0.5 });
		const auto alignSel = [&](float x, float y) {
			if (!isDraftSelValid()) return;
			auto& el = els[m_selectedElement];
			if (x >= 0) el.posX = x;
			if (y >= 0) el.posY = y;
			m_draftTexDirty = true;
		};
		if (ui.button(U"左", false, 26)) alignSel(0.08f, -1);
		if (ui.button(U"中", false, 26)) alignSel(0.50f, -1);
		if (ui.button(U"右", false, 26)) alignSel(0.92f, -1);
		if (ui.button(U"上", false, 26)) alignSel(-1, 0.10f);
		if (ui.button(U"央", false, 26)) alignSel(-1, 0.50f);
		if (ui.button(U"下", false, 26)) alignSel(-1, 0.90f);
	});

	// ── 均等配置 ──
	if (els.size() >= 3)
	{
		ui.row(2, [&] {
			ui.label(U"均等:", ColorF{ 0.5 });
			const auto distrib = [&](bool horizontal) {
				const int n = static_cast<int>(els.size());
				Array<int> ord(n); std::iota(ord.begin(), ord.end(), 0);
				if (horizontal)
					ord.sort_by([&](int a, int b) { return els[a].posX < els[b].posX; });
				else
					ord.sort_by([&](int a, int b) { return els[a].posY < els[b].posY; });
				const float mn = horizontal ? els[ord.front()].posX : els[ord.front()].posY;
				const float mx = horizontal ? els[ord.back()].posX  : els[ord.back()].posY;
				for (int i = 0; i < n; ++i)
				{
					float v = mn + (mx - mn) * i / (n - 1);
					if (horizontal) els[ord[i]].posX = v;
					else            els[ord[i]].posY = v;
				}
				m_draftTexDirty = true;
			};
			if (ui.button(U"水平", false, 40)) { distrib(true); }
			if (ui.button(U"垂直", false, 40)) { distrib(false); }
		});
	}

	// ── WYSIWYG プレビュー（beginContent 前に生成済みの m_draftTex を表示）──
	ui.spacer(4);
	if (m_draftTex)
	{
		const int panelW   = static_cast<int>(panelManager.getSize(U"guide_sign_editor").x) - 16;
		const double scale = Min(1.0, static_cast<double>(panelW) / m_draftTex.width());
		const int    drawH = static_cast<int>(m_draftTex.height() * scale);
		const double previewW = m_draftTex.width() * scale;
		const double previewX = 8.0;
		const double previewY = static_cast<double>(ui.height());
		const RectF  previewRect{ previewX, previewY, previewW, static_cast<double>(drawH) };

		m_draftTex.scaled(scale).draw(previewX, previewY);

		const Vec2 mousePos = Cursor::PosF();

		// 選択ハイライト（回転後外接四角形）
		if (isDraftSelValid())
		{
			const auto& sel = els[m_selectedElement];
			const double scaleX = previewW / m_draftTex.width();
			const double scaleY = static_cast<double>(drawH) / m_draftTex.height();
			const Vec2 center{ previewX + sel.posX * previewW, previewY + sel.posY * drawH };

			if (sel.kind == SignElementKind::Arrow)
			{
				// drawArrow と同じ 7 頂点を生成してスクリーン座標に変換し AABB を計算
				// posX/posY は始点（シャフト末端）、arrowLength は全長 [px]
				const double length   = sel.arrowLength;
				const double shaftH   = GuideSign::kArrowShaftWidth * 0.5;
				const double headH    = GuideSign::kArrowHeadWidth  * 0.5;
				const double shaftLen = Max(0.0, length - GuideSign::kArrowHeadHeight);
				const Array<Vec2> localPts = {
					{-shaftH,  0.0      }, {-shaftH, -shaftLen}, {-headH, -shaftLen},
					{ 0.0,    -length   },
					{+headH,  -shaftLen }, {+shaftH, -shaftLen }, {+shaftH,  0.0    }
				};
				const Mat3x2 rot = Mat3x2::Rotate(Math::ToRadians(sel.arrowAngle));
				double minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
				for (const auto& p : localPts)
				{
					const Vec2 r = rot.transformPoint(p);
					minX = Min(minX, r.x); maxX = Max(maxX, r.x);
					minY = Min(minY, r.y); maxY = Max(maxY, r.y);
				}
				RectF{ center.x + minX * scaleX, center.y + minY * scaleY,
				       (maxX - minX) * scaleX, (maxY - minY) * scaleY }
					.drawFrame(kSelectionHighlightThickness, kSelectionHighlightColor);
			}
			else if (sel.kind == SignElementKind::DestName)
			{
				const double th = sel.scale * m_draftTex.height();
				const double tw = FontAsset(Asset::CJK32Bold)(sel.text).region(th).w * scaleX;
				const double h  = th * scaleY;
				RectF{ center.x, center.y - h * 0.5, tw, h }
					.drawFrame(kSelectionHighlightThickness, kSelectionHighlightColor);
			}
			else if (sel.kind == SignElementKind::DestDistance)
			{
				const double th = sel.scale * m_draftTex.height() * (44.0 / 52.0);
				const double tw = FontAsset(Asset::Arial24)(U"{:.0f} km"_fmt(sel.value)).region(th).w * scaleX;
				const double h  = th * scaleY;
				RectF{ center.x - tw, center.y - h * 0.5, tw, h }
					.drawFrame(kSelectionHighlightThickness, kSelectionHighlightColor);
			}
			else
			{
				const double th = GuideSignLayout::DirectionArrow::UpTextH * m_draftTex.height() * sel.scale;
				const auto   rgn = FontAsset(Asset::CJK32Bold)(sel.text).region(th);
				RectF{ center.x - rgn.w * 0.5 * scaleX, center.y - rgn.h * 0.5 * scaleY,
				       rgn.w * scaleX, rgn.h * scaleY }
					.drawFrame(kSelectionHighlightThickness, kSelectionHighlightColor);
			}
		}

		// クリック: 選択 + ドラッグ開始
		if (previewRect.mouseOver() && MouseL.down())
		{
			m_selectedElement = -1;
			m_dragging = false;
			double bestD2 = kClickHitRadiusSq;
			for (int i = 0; i < static_cast<int>(els.size()); ++i)
			{
				const auto& eli = els[i];
				const double anchorX = previewX + eli.posX * previewW;
				const double anchorY = previewY + eli.posY * drawH;
				Vec2 testCenter{ anchorX, anchorY };
				if (eli.kind == SignElementKind::DestName)
				{
					const double th = eli.scale * m_draftTex.height();
					const double tw = FontAsset(Asset::CJK32Bold)(eli.text).region(th).w * scale;
					testCenter.x = anchorX + tw * 0.5;
				}
				else if (eli.kind == SignElementKind::DestDistance)
				{
					const double th = eli.scale * m_draftTex.height() * (44.0 / 52.0);
					const double tw = FontAsset(Asset::Arial24)(U"{:.0f} km"_fmt(eli.value)).region(th).w * scale;
					testCenter.x = anchorX - tw * 0.5;
				}
				const double d2 = mousePos.distanceFromSq(testCenter);
				if (d2 < bestD2) { bestD2 = d2; m_selectedElement = i; }
			}
			if (isDraftSelValid())
			{
				auto& el = els[m_selectedElement];
				m_dragOffset = Vec2{ previewX + el.posX * previewW, previewY + el.posY * drawH } - mousePos;
				m_dragStartNorm = Vec2{ el.posX, el.posY };
				m_dragging = true;
				m_copyDrag = KeyControl.pressed();
				if (m_copyDrag)
				{
					els << els[m_selectedElement];
					m_selectedElement = static_cast<int>(els.size()) - 1;
				}
			}
		}

		// ドラッグ移動
		if (m_dragging && MouseL.pressed() && isDraftSelValid())
		{
			auto& el = els[m_selectedElement];
			const Vec2 ns = mousePos + m_dragOffset;
			float nx = static_cast<float>(Clamp((ns.x - previewX) / previewW, 0.0, 1.0));
			float ny = static_cast<float>(Clamp((ns.y - previewY) / drawH, 0.0, 1.0));
			if (KeyShift.pressed())
			{
				if (std::abs(nx - m_dragStartNorm.x) > std::abs(ny - m_dragStartNorm.y))
					ny = static_cast<float>(m_dragStartNorm.y);
				else
					nx = static_cast<float>(m_dragStartNorm.x);
			}
			if (el.posX != nx || el.posY != ny)
			{
				el.posX = nx; el.posY = ny;
				m_draftTexDirty = true;
			}
		}
		if (MouseL.up()) { m_dragging = false; m_copyDrag = false; }

		// 矢印キー / Delete
		if (isDraftSelValid())
		{
			auto& el = els[m_selectedElement];
			const float step = KeyShift.pressed() ? kArrowKeyShiftStepPx : kArrowKeyStepPx;
			const float dx = step / static_cast<float>(previewW);
			const float dy = step / static_cast<float>(drawH);
			if (KeyUp.down())    { el.posY = Max(0.0f, el.posY - dy); m_draftTexDirty = true; }
			if (KeyDown.down())  { el.posY = Min(1.0f, el.posY + dy); m_draftTexDirty = true; }
			if (KeyLeft.down())  { el.posX = Max(0.0f, el.posX - dx); m_draftTexDirty = true; }
			if (KeyRight.down()) { el.posX = Min(1.0f, el.posX + dx); m_draftTexDirty = true; }
			if (KeyDelete.down())
			{
				deleteSelectedElement();
			}
		}

		// ホイール: 矢印回転
		if (isDraftSelValid() && els[m_selectedElement].kind == SignElementKind::Arrow
			&& previewRect.mouseOver())
		{
			const int wh = static_cast<int>(Mouse::Wheel());
			if (wh != 0)
			{
				auto& a = els[m_selectedElement].arrowAngle;
				a += wh * kArrowWheelRotateDeg;
				while (a < 0.0f)    a += 360.0f;
				while (a >= 360.0f) a -= 360.0f;
				m_draftTexDirty = true;
			}
		}

		ui.spacer(drawH + 4);
	}

	// ── 選択変化時: テキスト入力状態をリセット ──
	if (m_selectedElement != m_lastSelectedElement)
	{
		m_textEditState    = TextEditState{};
		m_readingEditState = TextEditState{};
		if (isDraftSelValid())
		{
			m_textEditState.text    = els[m_selectedElement].text;
			m_readingEditState.text = els[m_selectedElement].reading;
		}
		m_lastSelectedElement = m_selectedElement;
	}

	// ── 選択中プロパティ ──
	ui.spacer(2);
	if (isDraftSelValid())
	{
		auto& sel = els[m_selectedElement];
		if (sel.kind == SignElementKind::Arrow)
		{
			ui.row(4, [&] {
				ui.label(U"角度:", ColorF{ 0.6 });
				if (ui.numberInput(sel.arrowAngle, 15.0f, 0.0f, 360.0f, U"{:.0f}°", 50))
					m_draftTexDirty = true;
				ui.label(U"長さ:", ColorF{ 0.6 });
				if (ui.numberInput(sel.arrowLength, 0.5f, 0.5f, 10.0f, U"{:.1f}", 40))
					m_draftTexDirty = true;
			});
		}
		else if (sel.kind == SignElementKind::DestName)
		{
			ui.row(2, [&] {
				ui.label(U"大きさ:", ColorF{ 0.6 });
				if (ui.numberInput(sel.scale, 0.005f, 0.01f, 0.5f, U"{:.3f}", 50))
					m_draftTexDirty = true;
			});
			ui.row(2, [&] {
				ui.label(U"地名:", ColorF{ 0.6 });
				ui.textInput(m_textEditState, 0, 16);
				if (m_textEditState.text != sel.text)
				{
					sel.text = m_textEditState.text;
					m_draftTexDirty = true;
				}
			});
			ui.row(2, [&] {
				ui.label(U"読み(英):", ColorF{ 0.6 });
				ui.textInput(m_readingEditState, 0, 24);
				if (m_readingEditState.text != sel.reading)
				{
					sel.reading = m_readingEditState.text;
					m_draftTexDirty = true;
				}
			});
		}
		else if (sel.kind == SignElementKind::DestDistance)
		{
			ui.row(2, [&] {
				ui.label(U"大きさ:", ColorF{ 0.6 });
				if (ui.numberInput(sel.scale, 0.005f, 0.01f, 0.5f, U"{:.3f}", 50))
					m_draftTexDirty = true;
			});
			ui.row(2, [&] {
				ui.label(U"距離(km):", ColorF{ 0.6 });
				if (ui.numberInput(sel.value, 1.0f, 0.0f, 999.0f, U"{:.0f}", 50))
					m_draftTexDirty = true;
			});
			ui.row(2, [&] {
				ui.label(U"地名(参照):", ColorF{ 0.5 });
				ui.label(sel.text, ColorF{ 0.7 });
			});
		}
		else
		{
			ui.row(2, [&] {
				ui.label(U"大きさ:", ColorF{ 0.6 });
				if (ui.numberInput(sel.scale, 0.1f, 0.2f, 5.0f, U"{:.1f}", 40))
					m_draftTexDirty = true;
			});
			ui.row(2, [&] {
				ui.label(U"テキスト:", ColorF{ 0.6 });
				ui.textInput(m_textEditState, 0, 16);
				if (m_textEditState.text != sel.text)
				{
					sel.text = m_textEditState.text;
					m_draftTexDirty = true;
				}
			});
			ui.row(2, [&] {
				ui.label(U"読み(英):", ColorF{ 0.6 });
				ui.textInput(m_readingEditState, 0, 24);
				if (m_readingEditState.text != sel.reading)
				{
					sel.reading = m_readingEditState.text;
					m_draftTexDirty = true;
				}
			});
		}
	}
	else
	{
		ui.row(1, [&] { ui.label(U"(未選択)", ColorF{ 0.4 }); });
	}

	ui.flush();
	panelManager.reportContentHeight(U"guide_sign_editor", ui.height());

	if (closeRequested)
	{
		// draft を g.elements に書き戻し（commit）
		g.elements = std::move(m_draftElements);
		g.autoGenerated = false;
		m_draftElements.clear();
		m_draftValid         = false;
		m_draftTex           = RenderTexture{};
		m_draftTexDirty      = true;
		m_selectedElement    = -1;
		m_lastSelectedElement = -1;
		// guide_sign_edit (プロパティパネル) は閉じない
		panelManager.hide(U"guide_sign_editor");
	}
	return dirty;
}

