"""Replace coarse legacy OBJ variants with dimensional variants of the local detailed pack.

No external downloads. UVs and baked materials remain shared with the original pack.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]
BACKUP = ROOT / 'artifacts/city_realism/legacy_asset_baseline'

def save(path, data):
    backup = BACKUP / path.relative_to(ROOT)
    if path.exists() and not backup.exists():
        backup.parent.mkdir(parents=True, exist_ok=True)
        backup.write_bytes(path.read_bytes())
    path.write_bytes(data)

variants = [
    ('residential', 'residential_001', 'residential_011', (0.94, 0.96, 1.02)),
    ('residential', 'residential_002', 'residential_012', (1.03, 0.95, 0.94)),
    ('residential', 'residential_003', 'residential_013', (0.94, 1.04, 1.02)),
    ('residential', 'residential_004', 'residential_014', (1.02, 1.03, 0.94)),
    ('residential', 'residential_005', 'residential_015', (0.94, 0.96, 1.00)),
    ('residential', 'residential_006', 'residential_016', (1.00, 1.03, 0.94)),
    ('residential', 'residential_007', 'residential_017', (0.94, 0.94, 1.00)),
    ('residential', 'residential_008', 'residential_017', (1.00, 1.02, 0.94)),
    ('residential', 'residential_009', 'residential_018', (0.94, 0.90, 1.00)),
    ('residential', 'residential_010', 'residential_018', (1.00, 0.98, 0.94)),
    ('commercial', 'office_001', 'office_003', (0.96, 0.94, 1.00)),
    ('commercial', 'office_002', 'office_004', (1.00, 0.94, 0.96)),
]

for folder, target, source, scale in variants:
    base = ROOT / 'App/assets/buildings' / folder
    lines = [f'# Detailed variant of {source}; generated by scripts/refine_legacy_buildings.py']
    for line in (base / f'{source}.obj').read_text(encoding='utf-8-sig').splitlines():
        if line.startswith('v '):
            values = [float(value) * factor for value, factor in zip(line.split()[1:4], scale)]
            line = 'v ' + ' '.join(f'{value:.6f}' for value in values)
        elif line.startswith('vn '):
            values = [float(value) / factor for value, factor in zip(line.split()[1:4], scale)]
            length = math.sqrt(sum(value * value for value in values)) or 1.0
            line = 'vn ' + ' '.join(f'{value / length:.6f}' for value in values)
        elif line.startswith('mtllib '):
            line = f'mtllib {target}.mtl'
        elif line.startswith('o '):
            line = f'o {target}'
        lines.append(line)
    save(base / f'{target}.obj', ('\r\n'.join(lines)+'\r\n').encode('utf-8'))
    material = (base / f'{source}.mtl').read_text(encoding='utf-8-sig')
    save(base / f'{target}.mtl', material.replace('\n', '\r\n').encode('utf-8'))
    metadata = '# Detailed local-pack variant; metres; front -Z\r\nsetback_from_road_m = 1.8\r\nscale = 1.0\r\n'
    save(base / f'{target}.toml', metadata.encode('utf-8'))
    print(f'{target} <- {source}')
